### ISSUE TITLE
API 2.0

### ISSUE THREAD

**Issue by ai** [icyphox/nanoid.nim#2]
Let’s update the library to be compatible with the latest Nano ID 2.0:

- [x] Replace `~` to `-` in default alphabet
- [x] Add `non-secure` fast generator
- [ ] Async API?

**Comment by icyphox** [comment]
Sounds like a plan.

**Comment by icyphox** [comment]
I'm not _too_ familiar with Nim's async functionality yet, so the async API will have to be put on hold for now.

**Comment by icyphox** [comment]
Further, I believe async functionality isn't all too important to this lang's userbase. I'll add it in later though, but for now, I'll release 2.0 without it.
